# a simple Travis-CI Free Pascal example
language: generic

sudo: true
dist: trusty
group: edge

os:
  - linux
  - osx

notifications:
  email: false

git:
  depth: 3


before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        brew update;
        brew install fpc;
      else
        sudo apt install fp-compiler;
      fi

script: fpc im.pas

